// Run with playwright-cli run-code against an isolated issue web server.
async page => {
  const checks=[],errors=[];
  const check=(ok,name)=>{if(!ok)throw Error(name);checks.push(name);};
  page.on('pageerror',e=>errors.push(e.message));
  await page.reload();
  if(!await page.locator('#artifact-editor').count())await page.getByRole('button',{name:'New artifact',exact:true}).click();
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Browser plan');
  await page.getByRole('textbox',{name:'Markdown',exact:true}).fill('# Plan\n\n🐈'+'A'.repeat(79)+'**selected** phrase.\n\n- [x] Verified');
  await page.reload();
  await page.getByRole('textbox',{name:'Title',exact:true}).waitFor();
  check(await page.getByRole('textbox',{name:'Title',exact:true}).inputValue()==='Browser plan','New draft survives reload');
  await page.getByRole('button',{name:'Preview',exact:true}).click();
  await page.locator('#artifact-edit-preview strong').waitFor();
  check(await page.locator('#artifact-edit-preview strong').innerText()==='selected','Markdown preview renders formatting');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.locator('#artifact-reading strong').waitFor();
  const documentURL=page.url();
  const {project,id,origin}=await page.evaluate(()=>{const p=new URLSearchParams(location.hash.slice(1));return {project:p.get('project'),id:p.get('artifact'),origin:location.origin};});
  check(!!id,'Created document has stable URL');
  await page.evaluate(()=>{const text=document.querySelector('#artifact-reading strong').firstChild,range=document.createRange();range.selectNodeContents(text);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.querySelector('#artifact-reading').dispatchEvent(new Event('pointerup'));});
  check(await page.locator('#artifact-quote').innerText()==='selected','Unicode context anchors comment to rendered text');
  await page.getByRole('textbox',{name:'Add a comment',exact:true}).fill('Anchored discussion');
  await page.getByRole('button',{name:'Comment',exact:true}).click();
  await page.getByText('Anchored discussion',{exact:true}).waitFor();
  check(await page.locator('.artifact-thread blockquote').innerText()==='selected','Saved quote survives reading refresh');
  check(await page.getByText('Outdated selection · discussion preserved',{exact:true}).count()===0,'Formatted selection matches saved source');
  await page.getByRole('textbox',{name:'Reply to comment'}).fill('Follow up');
  await page.getByRole('button',{name:'Reply',exact:true}).click();
  await page.getByText('Follow up',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Resolve',exact:true}).click();
  await page.locator('details.artifact-thread.resolved').waitFor();
  check(!await page.locator('details.artifact-thread.resolved').getAttribute('open'),'Resolved discussion collapses');
  await page.reload();await page.locator('details.artifact-thread.resolved').waitFor();
  check(await page.locator('details.artifact-thread.resolved .reply').count()===1,'Resolved thread and reply persist after reload');
  await page.getByRole('button',{name:'Edit / rename',exact:true}).click();
  await page.getByRole('textbox',{name:'Markdown',exact:true}).fill('My merged draft');
  const boot=await(await page.request.get(origin+'/api/bootstrap')).json();
  const action=async operation=>{const r=await page.request.post(origin+'/api/action',{headers:{'X-Hey-Boss-CSRF':boot.csrf},data:{project,operation,request_id:await page.evaluate(()=>crypto.randomUUID())}});if(!r.ok())throw Error(await r.text());return r.json();};
  await action({action:'artifact',operation:{command:'edit',id,title:'Concurrent title',body:'Other device text',if_version:1}});
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.getByRole('button',{name:'Load latest for comparison',exact:true}).waitFor();
  check(await page.getByRole('textbox',{name:'Markdown',exact:true}).inputValue()==='My merged draft','Concurrent edit rejects overwrite and preserves draft');
  await page.getByRole('button',{name:'Load latest for comparison',exact:true}).click();
  await page.getByText('Other device text',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Use revision 2 for merged draft',exact:true}).click();
  await page.getByRole('textbox',{name:'Title',exact:true}).fill('Renamed browser plan');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await page.locator('#artifact-reading').waitFor();
  check(page.url()===documentURL,'Rename preserves URL');
  await page.locator('details.artifact-thread summary').click();
  check(await page.getByText('Outdated selection · discussion preserved',{exact:true}).isVisible(),'Removed selection becomes outdated without losing discussion');
  const issue=await action({action:'create',title:'Referring issue',body:'Issue description',labels:[]});
  const number=issue.issue.number;
  await action({action:'artifact',operation:{command:'link',id,issue:number}});
  await page.goto(origin+'/#project='+encodeURIComponent(project)+'&issue='+number);
  await page.locator('#issue-artifacts a').filter({hasText:'Renamed browser plan'}).waitFor();
  check(await page.locator('#issue-artifacts a').filter({hasText:'Renamed browser plan'}).count()===1,'Issue attachment displays renamed shared document');
  await page.locator('#issue-artifacts a').filter({hasText:'Renamed browser plan'}).click();
  await page.getByRole('link',{name:`Referring issue · #${number}`,exact:true}).waitFor();
  check(true,'Document backlink opens referring issue');
  await page.getByRole('button',{name:'Archive',exact:true}).click();
  await page.getByRole('button',{name:'Restore',exact:true}).waitFor();
  await page.getByRole('button',{name:'Restore',exact:true}).click();
  await page.getByRole('button',{name:'Archive',exact:true}).waitFor();
  check(true,'Archive and restore preserve document');
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Phone reading layout has no page overflow');
  check(errors.length===0,'No browser script errors');
  return {checks,project,id,issue:number};
}
