// Start both worker fixture servers, then run with playwright-cli run-code --filename.
async page => {
  const checks=[],errors=[];
  const check=(condition,label)=>{if(!condition)throw Error(label);checks.push(label);};
  page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1440,height:1050});
  await page.goto('http://127.0.0.1:59688/workers');
  await page.locator('.activity-machine').first().waitFor();
  check(await page.locator('.fleet-stat').count()===0,'Aggregate number cards are removed');
  check(await page.locator('.activity-worker').count()===7,'Stopped definitions and independent workers stay out of activity');
  check(await page.locator('.worker-scope-group').count()===4,'Workers are grouped by their complete project combination');
  check(await page.locator('.activity-worker:visible').count()===0,'Project groups start collapsed, hiding repeated worker rows');
  const shared=page.getByRole('heading',{name:'ashby-mcp + hey-gh + hey-proxy',exact:true});
  check(await shared.count()===1,'The shared project combination appears once');
  check((await shared.locator('..').innerText()).includes('3 workers'),'The shared combination contains all three workers');
  await page.locator('[data-host="local"] .worker-scope-heading').first().click();
  check(await page.locator('.activity-worker[open]').count()===0,'Workers begin as compact rows with details collapsed');
  check((await page.locator('.activity-machine-usage').allTextContents()).join('|')==='2 occupied · 10 available|1 occupied · 0 available · 1 paused|Last known activity','Shared-worker capacity is counted once');
  check(await page.locator('[data-worker="poe-code"] .activity-current-note').isVisible(),'Brief agent activity is visible in the worker row');
  check((await page.locator('.worker-scope-heading').first().boundingBox()).y<400,'Groups appear near the top of the page');
  check((await page.locator('[data-worker="paused"] .worker-state').textContent())==='Finishing work','Paused worker with an active agent is finishing work');
  await page.locator('[data-worker="poe-code"]>summary').click();
  check(await page.locator('.activity-task:visible').count()===2,'Expanding a worker reveals its task list');
  check(await page.getByText('Organizers · outside agent slots').isVisible(),'Organizers have a separate disclosure');
  await page.locator('.activity-task').first().focus();
  await page.waitForTimeout(3300);
  check(await page.locator('.activity-task').first().evaluate(el=>document.activeElement===el),'Refresh preserves expanded details and keyboard focus');
  await page.locator('[data-worker="poe-code"]>summary').click();
  await page.locator('[data-host="local"] .worker-scope-heading').first().click();
  await page.waitForTimeout(3300);
  check(await page.locator('.activity-worker:visible').count()===0,'Collapsed project groups stay collapsed across refresh');
  await page.locator('[data-host="local"]>.activity-machine-heading').click();
  await page.waitForTimeout(3300);
  check(!await page.locator('[data-host="local"]').evaluate(el=>el.open),'A collapsed machine stays collapsed across refresh');
  await page.locator('[data-host="local"]>.activity-machine-heading').click();
  await page.locator('[data-activity-filter="busy"]').click();
  check(await page.locator('.activity-worker').count()===2,'Working filter shows workers with occupied live slots');
  await page.locator('[data-activity-filter="all"]').click();
  await page.locator('#worker-search').fill('keyboard navigation');
  check(await page.locator('.activity-worker').count()===1,'Search finds the current agent activity');
  await page.locator('#worker-search').fill('');
  await page.screenshot({path:'output/playwright/workers-structure/activity-desktop.png',fullPage:true});
  await page.emulateMedia({colorScheme:'dark'});
  await page.screenshot({path:'output/playwright/workers-structure/activity-dark.png',fullPage:true});
  for(const width of [390,320]){
    await page.setViewportSize({width,height:844});
    check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),width+'px activity fits without horizontal scrolling');
    if(width===390)await page.screenshot({path:'output/playwright/workers-structure/activity-phone.png',fullPage:true});
  }
  await page.locator('#worker-config-view').click();
  check(await page.locator('.settings-scope').count()===4,'Settings uses the same project-combination grouping');
  await page.locator('[data-host="local"] .worker-scope-heading').first().click();
  check(await page.locator('.stopped-workers').count()===1,'Stopped definitions are grouped in management');
  check(!await page.locator('.stopped-workers').evaluate(el=>el.open),'Stopped group begins collapsed');
  await page.locator('[data-filter="stopped"]').click();
  check(await page.locator('.worker-record').count()===36,'Stopped filter reveals all saved definitions');
  await page.request.get('http://127.0.0.1:59688/fixture/missing-details');
  await page.goto('http://127.0.0.1:59688/workers');
  const busyShared=page.locator('.worker-scope-group').filter({has:page.getByRole('heading',{name:'ashby-mcp + hey-gh + hey-proxy',exact:true})});
  check(await busyShared.locator('.scope-current-task').innerText()==='Working · task details unavailable','Occupied group without task details reports work');
  await busyShared.locator('summary').first().click();
  const duplicateNames=await busyShared.locator('.activity-worker-name').allTextContents();
  check(new Set(duplicateNames).size===3,'Same-named workers have distinct visible identities');
  check((await busyShared.locator('.activity-current-note').allTextContents()).every(s=>s==='Working · task details unavailable'),'Worker rows also report occupied slots without task details');
  await page.setViewportSize({width:1440,height:1050});
  await page.goto('http://127.0.0.1:59648/workers#view=configuration',{waitUntil:'domcontentloaded'});
  await page.locator('.worker-scope-heading').click();
  await page.locator('[data-edit-worker="tools"]').click();
  await page.locator('#worker-editor').waitFor({state:'visible'});
  await page.locator('#worker-slots').fill('0');
  check(!await page.locator('#worker-slots').evaluate(el=>el.checkValidity()),'Structured form rejects zero slots');
  await page.locator('#worker-slots').fill('3');
  await page.locator('#worker-name').fill('Review worker');
  await page.locator('#worker-editor-preview').click();
  await page.waitForFunction(()=>!document.getElementById('worker-editor-save').disabled);
  check((await page.locator('#worker-editor-changes').innerText()).includes('2 → 3'),'Review shows the exact slot change');
  await page.screenshot({path:'output/playwright/workers-structure/settings-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Structured form fits on a phone');
  await page.screenshot({path:'output/playwright/workers-structure/settings-phone.png',fullPage:true});
  await page.locator('#worker-editor-save').click();
  await page.locator('#worker-editor').waitFor({state:'hidden'});
  const saved=await page.evaluate(()=>fetch('/api/fleet/configuration').then(r=>r.json()));
  check(saved.document.machines.local.workers[0].config.concurrency===3&&saved.document.machines.local.workers[0].config.name==='Review worker','Form writes the worker settings to authoritative YAML');
  await page.locator('[data-edit-worker="tools"]').click();
  await page.locator('#worker-editor').waitFor({state:'visible'});
  await page.locator('#worker-name').fill('Unsaved draft');
  const external=await page.evaluate(async c=>{const bootstrap=await fetch('/api/bootstrap').then(r=>r.json());return fetch('/api/fleet/configuration',{method:'POST',headers:{'Content-Type':'application/json','X-Hey-Boss-CSRF':bootstrap.csrf},body:JSON.stringify({text:c.text+'# external edit\n',revision:c.revision,save:true})}).then(r=>r.json());},saved);
  check(external.ok,'External fixture edit succeeded');
  await page.locator('#worker-editor-preview').click();
  await page.waitForFunction(()=>document.getElementById('worker-editor-status').textContent.includes('changed'));
  check(await page.locator('#worker-name').inputValue()==='Unsaved draft'&&await page.locator('#worker-editor-save').isDisabled(),'Stale form retains its draft and blocks saving');
  await page.locator('#worker-name').fill('Review worker');
  await page.locator('#worker-editor-cancel').click();
  await page.locator('#config-editor>summary').click();
  await page.waitForFunction(()=>!document.getElementById('config-text').disabled);
  const original=await page.locator('#config-text').inputValue();
  await page.locator('#config-text').fill('machines: [');
  await page.locator('#config-validate').click();
  await page.waitForFunction(()=>!document.getElementById('config-validate').disabled);
  check(await page.locator('#config-save').isDisabled(),'Advanced YAML still validates before saving');
  await page.locator('#config-text').fill(original);
  check(errors.length===0,'No browser JavaScript errors');
  return {passed:checks.length,checks};
}
