// Installed-command checks with disposable repositories and a synthetic ownership service.
import assert from 'node:assert/strict';
import {mkdtempSync, realpathSync, mkdirSync, writeFileSync, readFileSync, existsSync, copyFileSync, rmSync, constants} from 'node:fs';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
const root=realpathSync(mkdtempSync(join(tmpdir(),'cleanup-protection-')));
const checks=[];
try {
  const binary=join(root,'hey-harvester');
  copyFileSync(resolve(process.argv[2]||'target/debug/hey-harvester'),binary,constants.COPYFILE_FICLONE);
  const ownerFile=join(root,'owners.json');
  const owners=paths=>writeFileSync(ownerFile,JSON.stringify({version:2,worktrees:paths}));
  owners([]);
  writeFileSync(join(root,'hey-boss'),`#!/bin/sh\ncat '${ownerFile}'\n`,{mode:0o700});
  const env={...process.env,HOME:join(root,'home'),HEY_BOSS_HEALTH_DIR:join(root,'health')};
  mkdirSync(env.HOME);
  const run=(args,ok)=>{
    const r=spawnSync(binary,[...args,'--json'],{env,encoding:'utf8',timeout:180000});
    assert(!r.error,r.error?.message); assert.equal(r.status===0,ok,r.stderr+'\n'+r.stdout);
    const receipt=JSON.parse(r.stdout); assert.equal(receipt.decision,ok?'accepted':'rejected');
    return receipt;
  };
  const git=(cwd,...args)=>{
    const r=spawnSync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-C',cwd,...args],{encoding:'utf8'});
    assert.equal(r.status,0,r.stderr); return r.stdout.trim();
  };
  const repo=join(root,'repo');mkdirSync(repo);git(repo,'init','-b','main');
  writeFileSync(join(repo,'.gitignore'),'node_modules/\n');git(repo,'add','.');git(repo,'commit','-m','fixture');
  const work=join(root,'work');git(repo,'worktree','add','-b','disposable',work);
  const dependencies=join(work,'node_modules');mkdirSync(dependencies);writeFileSync(join(dependencies,'tsc'),'fixture');
  run(['cleanup-check',dependencies],true);
  checks.push('Dependencies without release metadata reach ordinary safety checks');
  writeFileSync(ownerFile,JSON.stringify({version:1,worktrees:[]}));
  assert.match(run(['remove-dependencies',dependencies],false).reason,/inventory v2/);
  assert(existsSync(join(dependencies,'tsc')));
  checks.push('Incomplete ownership inventory preserves dependencies');
  owners([work]);
  assert.match(run(['remove-dependencies',dependencies],false).reason,/owner/);
  owners([]);
  run(['cleanup-check',dependencies],true);
  owners([work]);
  assert.match(run(['remove-dependencies',dependencies],false).reason,/owner/);
  assert(existsSync(join(dependencies,'tsc')));
  checks.push('Ownership acquired after candidate discovery is rechecked at removal');
  owners([]);
  git(repo,'worktree','lock','--reason','queued validator; retain old dependencies',work);
  assert.match(run(['remove-dependencies',dependencies],false).reason,/queued validator/);
  assert(existsSync(join(dependencies,'tsc')));
  checks.push('A queued Git ownership lock protects dependencies');
  git(repo,'worktree','unlock',work);
  writeFileSync(join(dependencies,'logo.sketch'),Buffer.from('SQLite format 3\0fixture'));
  for(const action of ['cleanup-check','remove-dependencies']) {
    assert.match(run([action,dependencies],false).reason,/Protected dependency content/);
    assert(existsSync(join(dependencies,'logo.sketch')));
  }
  rmSync(join(dependencies,'logo.sketch'));
  checks.push('Dependency database assets remain protected, including disguised SQLite');
  git(work,'add','-f','node_modules/tsc');
  assert.match(run(['remove-dependencies',dependencies],false).reason,/Tracked dependency/);
  git(work,'reset','--','node_modules/tsc');
  run(['remove-dependencies',dependencies],true);assert(!existsSync(dependencies));
  checks.push('Disposable dependencies are removed without a release; tracked content survives');
  mkdirSync(dependencies);writeFileSync(join(dependencies,'tsc'),'rebuilt');
  owners([work]);
  assert.match(run(['remove-dependencies',dependencies],false).reason,/owner/);
  assert(existsSync(join(dependencies,'tsc')));
  owners([]);
  checks.push('Rebuilt dependencies remain protected by current ownership');
  const help=spawnSync(binary,['--help'],{encoding:'utf8'}).stdout;
  assert(!help.includes('release-cleanup')&&!help.includes('retain-cleanup'));
  checks.push('Obsolete release and retain commands are absent from help');
  const state=JSON.parse(readFileSync(join(root,'health/state.json'),'utf8'));
  const receipts=state.snapshot.activity.filter(e=>e.category==='cleanup-receipt').map(e=>JSON.parse(e.message));
  assert(receipts.some(e=>e.decision==='rejected'&&e.path===dependencies));
  assert(receipts.some(e=>e.action==='remove-dependencies'&&e.decision==='accepted'));
  checks.push('Both accepted and rejected outcomes have saved audit receipts');
  const bin=join(root,'bin');mkdirSync(bin);
  writeFileSync(join(bin,'ssh'),`#!/bin/sh\nprintf '%s\\n' '{"version":1,"decision":"rejected","reason":"Retained remote owner"}'\necho 'Retained remote owner' >&2\nexit 1\n`,{mode:0o700});
  env.PATH=bin+':'+process.env.PATH;
  assert.equal(run(['--host','fixture.invalid','cleanup-check',dependencies],false).reason,'Retained remote owner');
  checks.push('Remote CLI preserves JSON rejection receipts and a nonzero exit');
  console.log(JSON.stringify({normalCompletion:true,completed:checks.length,checks}));
} finally { rmSync(root,{recursive:true,force:true}); }
