// Installed-command checks with disposable repositories and a synthetic ownership service.
import assert from 'node:assert/strict';
import {mkdtempSync, realpathSync, mkdirSync, writeFileSync, readFileSync, existsSync, copyFileSync, rmSync, constants} from 'node:fs';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
const root=realpathSync(mkdtempSync(join(tmpdir(),'cleanup-protection-')));
const checks=[];
try {
  const binary=join(root,'hey-harvester');
  copyFileSync(resolve(process.argv[2]||'target/debug/hey-harvester'),binary,constants.COPYFILE_FICLONE);
  const ownerFile=join(root,'owners.json');
  const owners=paths=>writeFileSync(ownerFile,JSON.stringify({version:2,worktrees:paths}));
  owners([]);
  writeFileSync(join(root,'hey-boss'),`#!/bin/sh\ncat '${ownerFile}'\n`,{mode:0o700});
  const env={...process.env,HOME:join(root,'home'),HEY_BOSS_HEALTH_DIR:join(root,'health')};
  mkdirSync(env.HOME);
  const run=(args,ok)=>{
    const r=spawnSync(binary,[...args,'--json'],{env,encoding:'utf8',timeout:180000});
    assert(!r.error,r.error?.message); assert.equal(r.status===0,ok,r.stderr+'\n'+r.stdout);
    const receipt=JSON.parse(r.stdout); assert.equal(receipt.decision,ok?'accepted':'rejected');
    return receipt;
  };
  const git=(cwd,...args)=>{
    const r=spawnSync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','-C',cwd,...args],{encoding:'utf8'});
    assert.equal(r.status,0,r.stderr); return r.stdout.trim();
  };
  const repo=join(root,'repo');mkdirSync(repo);git(repo,'init','-b','main');
  writeFileSync(join(repo,'.gitignore'),'node_modules/\n');git(repo,'add','.');git(repo,'commit','-m','fixture');
  const work=join(root,'work');git(repo,'worktree','add','-b','disposable',work);
  const dependencies=join(work,'node_modules');mkdirSync(dependencies);writeFileSync(join(dependencies,'tsc'),'fixture');
  const rejection=run(['remove-dependencies',dependencies],false);
  assert.match(rejection.reason,/release/);assert(existsSync(join(dependencies,'tsc')));
  checks.push('Unreleased dependencies survive with a nonzero rejection receipt');
  writeFileSync(ownerFile,JSON.stringify({version:1,worktrees:[]}));
  assert.match(run(['release-cleanup',dependencies,'--owner','fixture-owner'],false).reason,/inventory v2/);
  assert(existsSync(join(dependencies,'tsc')));
  checks.push('An outdated ownership service cannot authorize a release');
  owners([work]);
  const active=run(['release-cleanup',dependencies,'--owner','fixture-owner'],false);
  assert.match(active.reason,/owner/);checks.push('Live declared ownership blocks even an explicit release');
  owners([]);
  run(['release-cleanup',dependencies,'--owner','fixture-owner'],true);
  run(['cleanup-check',dependencies],true);
  owners([work]);
  const changed=run(['remove-dependencies',dependencies],false);
  assert.match(changed.reason,/owner/);assert(existsSync(join(dependencies,'tsc')));
  checks.push('Ownership acquired after candidate discovery is rechecked at removal');
  owners([]);
  git(repo,'worktree','lock','--reason','queued validator; retain old dependencies',work);
  assert.match(run(['remove-dependencies',dependencies],false).reason,/queued validator/);
  assert(existsSync(join(dependencies,'tsc')));checks.push('A queued Git ownership lock protects dependencies');
  git(repo,'worktree','unlock',work);
  run(['retain-cleanup',dependencies],true);
  assert.match(run(['remove-dependencies',dependencies],false).reason,/release/);
  checks.push('Withdrawing a loaded release prevents removal');
  run(['release-cleanup',dependencies,'--owner','fixture-owner'],true);
  run(['remove-dependencies',dependencies],true);assert(!existsSync(dependencies));
  checks.push('Explicitly released disposable dependencies remain cleanable');
  mkdirSync(dependencies);writeFileSync(join(dependencies,'tsc'),'rebuilt');
  assert.match(run(['remove-dependencies',dependencies],false).reason,/release/);
  assert(existsSync(join(dependencies,'tsc')));checks.push('A consumed release cannot delete rebuilt dependencies');
  const state=JSON.parse(readFileSync(join(root,'health/state.json'),'utf8'));
  const receipts=state.snapshot.activity.filter(e=>e.category==='cleanup-receipt').map(e=>JSON.parse(e.message));
  assert(receipts.some(e=>e.decision==='rejected'&&e.path===dependencies));
  assert(receipts.some(e=>e.action==='remove-dependencies'&&e.decision==='accepted'));
  checks.push('Both accepted and rejected outcomes have saved audit receipts');
  console.log(JSON.stringify({normalCompletion:true,completed:checks.length,checks}));
} finally { rmSync(root,{recursive:true,force:true}); }
