// Run with playwright-cli against an isolated issue store, independently per browser.
async (page) => {
 page.on("dialog",d=>d.accept().catch(()=>{}));
 const origin=await page.evaluate(()=>location.origin),checks=[],errors=[];
 const check=(ok,name)=>{if(!ok)throw Error(name);checks.push(name)};
 page.on('pageerror',e=>errors.push(e.message));await page.reload();await page.waitForFunction(()=>!!model.csrf&&model.boss);
 const name='Alex <Boss> '+(await page.evaluate(()=>crypto.randomUUID().slice(0,6)));
 const projects=await page.evaluate(async()=>{const result=[];for(const suffix of ['Alpha','Beta']){const project=(await api({action:'create',title:'Keep assignment',body:'Preserve Markdown',labels:['ready']},'Global profile '+suffix+' '+crypto.randomUUID())).project.id;await api({action:'assign_boss',number:1,force:false},project);result.push(project)}return result});
 const go=async project=>{await page.goto(origin+'/#project='+encodeURIComponent(project));await page.waitForFunction(project=>model.project?.id===project&&model.signature&&model.issues.some(i=>i.number===1),project)};
 const open=async()=>{await page.locator('#self-avatar').click();await page.locator('#global-settings-trigger').click();await page.waitForFunction(()=>!document.querySelector('#global-boss-name').disabled)};
 await page.setViewportSize({width:1440,height:1000});await go(projects[0]);
 await page.locator('#self-avatar').focus();await page.keyboard.press('ArrowDown');check(await page.locator('#profile-menu').isVisible(),'Profile badge opens dropdown by keyboard');check(await page.locator('#global-settings-trigger').evaluate(el=>el===document.activeElement),'Dropdown focuses Settings');await page.keyboard.press('ArrowDown');check(await page.locator('#global-settings-trigger').evaluate(el=>el===document.activeElement),'Menu arrows retain focus on Settings');await page.keyboard.press('Escape');check(await page.locator('#profile-menu').isHidden(),'Escape closes profile dropdown');await page.locator('#self-avatar').click();await page.keyboard.press('Tab');check(await page.locator('#profile-menu').isHidden()&&await page.evaluate(()=>document.activeElement!==document.body&&document.activeElement.id!=='self-avatar'&&document.activeElement.id!=='global-settings-trigger'&&document.activeElement.checkVisibility()),'Tab closes dropdown and resumes page navigation');
 await open();check(await page.locator('#global-settings-submit').isDisabled(),'Unchanged settings cannot submit');await page.locator('#global-boss-name').fill(name);await page.locator('#global-settings-submit').click();await page.locator('#global-settings-dialog').waitFor({state:'hidden'});await page.waitForFunction(name=>document.querySelector('#profile-name').textContent===name&&document.querySelector('.list-assignee-filter > span:last-child')?.textContent===name,name);check(await page.locator('#self-avatar').innerText()==='AL','Badge reflects global name');check(await page.locator('.list-assignee-filter > span:last-child').innerText()===name,'Existing assignment displays global name');
 await go(projects[1]);check(await page.locator('.list-assignee-filter > span:last-child').innerText()===name,'Second project shares global name');check(await page.evaluate(()=>model.issues[0].assignee==='human:boss'&&model.issues[0].version===2),'Renaming preserves assignee identity and issue revision');await page.reload();await page.waitForFunction(name=>model.boss.name===name,name);check(await page.locator('#self-avatar').innerText()==='AL','Global name persists on reload');
 await page.locator('#project-settings-trigger').click();await page.waitForFunction(()=>!document.querySelector('#project-prompt').disabled);check(await page.locator('#project-boss-name').count()===0,'Project settings have no Boss name field');await page.locator('#project-settings-cancel').click();
 await open();await page.locator('#global-boss-name').fill('My preserved draft');await page.evaluate(async()=>{const settings=await api({action:'global_settings'});await api({action:'configure_global',boss_name:'Concurrent name',if_version:settings.version})});await page.locator('#global-settings-submit').click();await page.waitForSelector('#global-settings-reload:not([hidden])');check(await page.locator('#global-boss-name').inputValue()==='My preserved draft','Concurrent save preserves draft');await page.locator('#global-settings-reload').click();await page.waitForFunction(()=>globalSettingsOriginal==='Concurrent name');check(await page.locator('#global-boss-name').inputValue()==='My preserved draft','Reload current version preserves draft');await page.locator('#global-settings-submit').click();await page.locator('#global-settings-dialog').waitFor({state:'hidden'});check(await page.evaluate(()=>model.boss.name==='My preserved draft'),'Reloaded version can save safely');
 await page.setViewportSize({width:390,height:844});check(await page.locator('#self-avatar').isVisible(),'Profile badge remains accessible on mobile');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile header has no horizontal overflow');await open();check(await page.locator('#global-settings-dialog').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}),'Global settings dialog fits mobile');await page.keyboard.press('Escape');check(await page.locator('#self-avatar').evaluate(el=>el===document.activeElement),'Closing settings returns focus to profile');await page.setViewportSize({width:320,height:700});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Small phone header does not overflow');for(const [unicodeName,expected] of [['A😀','A😀'],['e\u0301mile','E\u0301M']]){await open();await page.locator('#global-boss-name').fill(unicodeName);await page.locator('#global-settings-submit').click();await page.locator('#global-settings-dialog').waitFor({state:'hidden'});await page.waitForFunction(expected=>document.querySelector('#self-avatar').textContent===expected&&document.querySelector('.list-assignee-filter .avatar')?.textContent===expected,expected);check(true,'Profile and assignee badges preserve '+unicodeName);}check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Unicode profile badges fit small phone');check(errors.length===0,'No JavaScript runtime errors');return {passed:checks.length,checks};
}
