// Run through playwright-cli on an isolated issue web server.
async (page) => {
 const origin=await page.evaluate(()=>location.origin),checks=[],errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const check=(ok,name)=>{if(!ok)throw Error(name);checks.push(name)};
 const project=await page.evaluate(async()=>{const name='Creation feedback '+crypto.randomUUID();return (await api({action:'create',title:'Existing ready issue',body:'',labels:['ready']},name)).project.id});
 const go=async params=>{await page.goto(origin+'/#project='+encodeURIComponent(project)+(params||''));await page.waitForFunction(project=>model.project?.id===project&&model.route.view==='issues',project)};
 const create=async(title)=>{await page.locator('#new-issue').click();await page.locator('#editor-subject').fill(title);await page.locator('#editor-submit').click();await page.waitForFunction(()=>!model.editor&&model.route.issue===null&&model.creation&&document.querySelector(`[data-issue-number="${model.creation.number}"].issue-created`));return Number(await page.locator('.issue-created').getAttribute('data-issue-number'))};
 await page.setViewportSize({width:1440,height:1000});await go();const n=await create('First new issue');check(await page.evaluate(()=>model.route.issue===null),'Creating does not navigate to detail');check(await page.locator('.issue-row').first().getAttribute('data-issue-number')===String(n),'New row is first');check(await page.locator('.issue-created .issue-title').evaluate(el=>el===document.activeElement),'New issue title receives keyboard focus');check(await page.locator('.issue-created').evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}),'Highlighted row is visible');
 await page.evaluate(()=>renderList({issues:model.issues,order_version:model.orderVersion}));check(await page.locator('.issue-created').count()===1,'Refresh preserves temporary highlight');await page.waitForFunction(()=>!model.creation&&!document.querySelector('.issue-created'),{timeout:6000});check(await page.locator(`.issue-row[data-issue-number="${n}"]`).count()===1,'Highlight expires while issue remains');
 await page.locator('.issue-title').first().click();await page.waitForSelector('[data-edit]');await page.locator('[data-edit]').click();await page.locator('#editor-subject').fill('Edited first issue');await page.locator('#editor-submit').click();await page.waitForFunction(()=>!model.editor&&model.detail?.issue.title==='Edited first issue');check(await page.evaluate(n=>model.route.issue===n,n),'Editing still stays on issue detail');
 await go('&label=ready&owner=unassigned');await page.waitForSelector('.issue-row');await page.locator('#new-issue').click();await page.locator('#editor-subject').fill('Matching ready issue');await page.evaluate(()=>editorTags.set(['ready']));await page.locator('#editor-submit').click();await page.waitForFunction(()=>!model.editor&&model.creation&&document.querySelector(`[data-issue-number="${model.creation.number}"].issue-created`));check(await page.evaluate(()=>model.route.label==='ready'&&model.route.owner==='unassigned'),'Matching list filters remain');
 const next=await create('No ready label');check(await page.evaluate(()=>model.route.label===''&&model.route.owner==='all'),'Excluding filters clear to reveal new issue');check(await page.locator('.issue-created').count()===1&&Number(await page.locator('.issue-created').getAttribute('data-issue-number'))===next,'Repeated creation highlights only newest issue');
 await go('&state=closed&owner=mine');await page.waitForSelector('[data-empty="clear"]');const closedCreate=await create('Created from closed tab');check(await page.evaluate(()=>model.route.state==='open'&&model.route.owner==='all'&&model.route.issue===null),'Creating from closed tab reveals new open issue in list');
 await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.setViewportSize({width:390,height:844});check(await page.locator('.issue-created').evaluate(el=>getComputedStyle(el).backgroundColor!==getComputedStyle(document.querySelector('#issue-list')).backgroundColor),'Highlight remains visible with reduced motion');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile highlighted list has no overflow');await page.screenshot({path:'output/playwright/issue-creation-feedback-'+(await page.evaluate(()=>navigator.userAgent.includes('Chrome')?'chrome':'webkit'))+'.png'});await page.reload();await page.waitForSelector('.issue-row');check(await page.locator('.issue-created').count()===0,'Reload does not resurrect expired creation feedback');check(await page.locator('.issue-row').first().getAttribute('data-issue-number')===String(closedCreate),'Creation order survives reload');check(errors.length===0,'No JavaScript runtime errors: '+errors.join('; '));return {passed:checks.length,checks};
}
