// Isolated issue stores only; every run creates its own project.
async page => {
 const checks=[],errors=[],check=(ok,name)=>{if(!ok)throw Error(name);checks.push(name)};
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept().catch(()=>{}));
 await page.reload();await page.waitForFunction(()=>model.csrf&&model.project);
 const origin=await page.evaluate(()=>location.origin);
 const project=await page.evaluate(async()=>{const r=await api({action:'create',title:'Ship the feature',body:'## Parent plan',labels:['ready']},'Subtask QA '+crypto.randomUUID());return r.project.id});
 const go=async number=>{await page.goto(origin+'/#project='+encodeURIComponent(project)+(number?'&issue='+number:''));await page.waitForFunction(({project,number})=>model.project?.id===project&&(number?model.detail?.issue.number===number:!!model.signature),{project,number})};
 const act=async operation=>page.evaluate(async({project,operation})=>await api(operation,project),{project,operation});
 const order=()=>page.locator('#subtask-list > li').evaluateAll(rows=>rows.map(r=>Number(r.dataset.issueNumber)));
 const load=async()=>{await page.locator('[data-reload]').click();await page.waitForFunction(()=>!document.querySelector('[data-reload]')&&model.detail)};
 await page.setViewportSize({width:1440,height:1000});await go(1);
 check(await page.locator('.subtasks-empty').innerText()==='No subtasks yet.','Empty parent has a clear subtask card');
 await page.locator('#comment-body').fill('Keep my parent comment draft');
 await page.locator('[data-create-subtask]').click();check(await page.locator('#editor-title').innerText()==='New subtask','Create uses the Markdown issue editor');
 await page.locator('#editor-subject').fill('Implement the first piece');await page.locator('#editor-body').fill('## Child plan\n\n- [ ] Verify the result');await page.locator('#editor-submit').click();
 await page.waitForFunction(()=>model.detail?.issue.number===1&&model.detail?.subtasks?.length===1);
 check(await page.evaluate(()=>model.route.issue===1),'Subtask creation stays with the parent');
 check(await page.locator('#subtask-list .issue-created').count()===1,'New child is highlighted temporarily');
 check(await page.locator('#comment-body').inputValue()==='Keep my parent comment draft','Child creation preserves the comment draft');
 check(await page.locator('#subtask-list .subtask-title').evaluate(el=>el===document.activeElement),'New child receives visible keyboard focus');
 await act({action:'edit',number:2,title:null,body:null,add_labels:['backend'],remove_labels:[],if_version:null});await act({action:'assign_boss',number:2,force:false});await act({action:'add_pull_request',number:2,url:'https://github.com/example/hey-boss/pull/42'});await go(1);
 check(await page.locator('#subtask-list .issue-pr-link').getAttribute('href')==='https://github.com/example/hey-boss/pull/42','Child PR is visible and directly clickable');
 await page.locator('#subtask-list .list-label-filter').click();await page.waitForFunction(()=>model.route.issue===null&&model.route.label==='backend'&&model.issues.length===1);check(await page.locator('#issue-list .issue-title').innerText()==='Implement the first piece','Child label filters the full queue');await go(1);
 await page.locator('#subtask-list .list-assignee-filter').click();await page.waitForFunction(()=>model.route.issue===null&&model.route.owner==='human:boss'&&model.issues.length===1);check(await page.locator('#issue-list .issue-title').innerText()==='Implement the first piece','Child assignee filters the full queue');await go(1);
 await page.locator('#subtask-list .subtask-title').click();await page.waitForFunction(()=>model.detail?.issue.number===2);
 check(await page.getByRole('heading',{name:'Child plan',exact:true}).isVisible(),'Child stores and renders proper Markdown');
 check(await page.locator('.parent-breadcrumb').innerText().then(t=>t.includes('#1 Ship the feature')),'Child has a readable parent breadcrumb');
 await page.locator('.parent-breadcrumb a').click();await page.waitForFunction(()=>model.detail?.issue.number===1);
 await act({action:'create',title:'Existing <piece>',body:'Keep this separate issue',labels:[]});await act({action:'close',number:3,force:false,comment:null});
 await page.locator('[data-add-existing-subtask]').click();await page.waitForSelector('[data-existing-subtask="3"]');
 check(await page.locator('[data-existing-subtask="1"]').isDisabled(),'Picker prevents linking the parent to itself');
 check(await page.locator('[data-existing-subtask="2"]').isDisabled(),'Picker shows already-linked issues as unavailable');
 await page.locator('#subtask-picker-search').fill('no matching title');check(await page.locator('.picker-empty').isVisible(),'Picker search has an empty state');
 await page.locator('#subtask-picker-search').fill('Existing');await page.keyboard.press('ArrowDown');check(await page.locator('[data-existing-subtask="3"]').evaluate(el=>el===document.activeElement),'Search supports keyboard selection');await page.keyboard.press('Enter');
 await page.waitForFunction(()=>model.detail?.issue.number===1&&model.detail?.subtasks?.length===2);
 check(await page.locator('#subtask-picker-dialog').isHidden(),'Successful link closes the picker');
 check(await page.locator('.subtask-progress-line').innerText().then(t=>t.includes('1 of 2 closed')),'Progress includes an existing closed child');
 check(await page.locator('#subtask-list .subtask-title').filter({hasText:'Existing <piece>'}).count()===1,'Issue titles remain escaped');
 await act({action:'create_subtask',number:3,title:'Nested leaf',body:'## Nested Markdown',labels:[],at_top:false,if_version:null});
 await go(4);check(await page.locator('.parent-breadcrumb').innerText().then(t=>t.includes('#3 Existing <piece>')),'Nested child navigates to its immediate parent');await go(1);
 check(await page.locator('.subtask-descendants').innerText()==='2 open issues across all levels','Closed intermediate children do not hide unfinished descendants');
 await page.locator('#comment-body').focus();await act({action:'close',number:2,force:false,comment:null});await page.locator('[data-reload]').waitFor();
 check(await page.locator('#comment-body').inputValue()==='Keep my parent comment draft','External child closure preserves draft');
 check(await page.locator('#comment-body').evaluate(el=>el===document.activeElement),'External child closure preserves typing focus');
 await page.keyboard.type(' continues');await load();check(await page.locator('#comment-body').inputValue()==='Keep my parent comment draft continues','Loading child changes restores the full draft');
 check(await page.locator('.subtask-progress-line').innerText().then(t=>t.includes('2 of 2 closed')),'Direct progress refreshes without closing the parent');
 check(await page.locator('.subtask-descendants').innerText()==='1 open issue across all levels','Open grandchild still appears in progress context');
 await act({action:'create',title:'Unrelated top issue',body:'Not part of this parent',labels:[],at_top:true});await page.waitForFunction(()=>!model.polling);await page.evaluate(()=>refresh(true));
 check(await page.locator('[data-reload]').count()===0,'Unrelated queue changes do not create a parent update banner');
 await page.locator('#subtask-list [data-move-issue="3"]').focus();await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>!model.orderSaving&&model.detail?.subtasks[0].number===3);
 check(JSON.stringify(await order())==='[3,2]','Keyboard subtask sorting respects queue order');
 check(await page.locator('#subtask-list [data-move-issue="3"]').evaluate(el=>el===document.activeElement),'Sorting restores focus to the visible child handle');
 check(await page.locator('#comment-body').inputValue()==='Keep my parent comment draft continues','Sorting preserves the comment draft');
 const handle=page.locator('#subtask-list [data-move-issue="3"]'),target=page.locator('#subtask-list [data-issue-number="2"]');await handle.scrollIntoViewIfNeeded();const from=await handle.boundingBox(),to=await target.boundingBox();
 await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height*.8,{steps:8});await page.mouse.up();await page.waitForFunction(()=>!model.orderSaving&&model.detail?.subtasks[0].number===2);
 check(JSON.stringify(await order())==='[2,3]','Pointer sorting shares the same persistent queue');
 await page.locator('[data-unlink-subtask="3"]').click();await page.waitForFunction(()=>model.detail?.subtasks.length===1);
 const unlinked=await act({action:'view',number:3});check(unlinked.issue.parent===null&&unlinked.issue.state==='closed'&&unlinked.issue.body==='Keep this separate issue','Unlink preserves the existing issue content and lifecycle');
 check((await act({action:'view',number:4})).issue.parent.number===3,'Unlink preserves the child subtree');
 await act({action:'delete',number:2,force:false});await page.locator('[data-reload]').waitFor();await load();
 check(await page.locator('.deleted-subtasks summary').innerText()==='1 deleted subtask','Deleted relationships stay available to unlink');
 check(await page.locator('.subtasks-empty').isVisible(),'Deleted children are excluded from visible progress');
 await page.locator('.deleted-subtasks summary').click();await page.locator('[data-unlink-subtask="2"]').click();await page.waitForFunction(()=>model.detail?.subtasks.length===0);
 check((await act({action:'view',number:2})).issue.parent===null,'Deleted child can be unlinked without restoration');
 await act({action:'create_subtask',number:1,title:('Long child 😀 '+ 'text ').repeat(15),body:'## Long title control',labels:[],at_top:false,if_version:null});await go(1);
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Subtask card fits '+width+'px');}
 await page.locator('[data-add-existing-subtask]').click();await page.waitForSelector('[data-existing-subtask="4"]');check(await page.locator('#subtask-picker-dialog').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}),'Picker fits narrow screens');await page.keyboard.press('Escape');check(await page.locator('[data-add-existing-subtask]').evaluate(el=>el===document.activeElement),'Closing picker restores visible focus');
 await page.setViewportSize({width:1440,height:1000});check(errors.length===0,'No browser runtime errors');
 return {passed:checks.length,checks,project};
}
