// Run through playwright-cli against serve_jobs_ui_fixture.mjs only.
async page => {
 const origin=await page.evaluate(()=>location.origin);
 if(!['http://127.0.0.1:59649','http://127.0.0.1:52049'].includes(origin))throw Error('Isolated fixture required');
 const params=value=>Object.entries(value).map(([k,v])=>encodeURIComponent(k)+'='+encodeURIComponent(v)).join('&');
 const paired=origin.endsWith('52049'),surface=paired?'paired':'desktop',project='named:Jobs UI QA',errors=[],checks=[];
 const check=(ok,name)=>{if(!ok)throw Error(name);checks.push(name);};
 page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
 page.on('dialog',dialog=>dialog.accept());
 const runtime=route=>{const provider=route.request().postDataJSON().provider||'codex';return route.fulfill({json:{ok:true,machine:'fixture-device',machines:[{state:'connected',heartbeat:Date.now()/1000,jobs:{available:true,checkouts:{[project]:'/fixture'},runtimes:{codex:{available:true},claude:{available:true},pi:{available:false}}},workers:[]}],catalog:{provider,error:provider==='pi'?'Pi runtime is unavailable':null,models:provider==='pi'?[]:[{selection:{id:provider+'-exact'},label:provider+' exact',advertised:true}]}}});};
 await page.route('**/api/jobs/runtime',runtime);
 await page.route('**/jobs.js',r=>r.fulfill({path:'src/issues/web/jobs.js',contentType:'text/javascript'}));
 await page.route('**/api/inbox',r=>r.fulfill({json:{ok:true,tasks:[],unread_count:0}}));
 if(paired){const {code}=await(await page.request.get(origin+'/fixture-pairing')).json();check((await page.request.post(origin+'/api/pair',{data:{code}})).ok(),'Authenticated paired surface');}
 const markdown=await(await page.request.get('http://127.0.0.1:52049/fixture-instructions.md')).text();
 await page.goto(origin+'/jobs?qa='+Date.now()+'#'+params({project}));
 await page.waitForFunction(()=>!document.querySelector('#job-new').disabled);
 check(await page.locator('#jobs-service').textContent()==='Job service available','Absent worker pool keeps Jobs available');
 let writes=0;const watch=req=>{if(req.url().endsWith('/api/action')&&['create','edit','run_now','stop','delete','set_enabled'].includes(req.postDataJSON()?.operation?.operation?.command))writes++;};page.on('request',watch);
 await page.getByRole('button',{name:'New job',exact:true}).click();
 await page.locator('#job-name').fill('Weekday repository review');
 await page.locator('#job-markdown').fill(markdown);
 await page.locator('#job-cron').fill('invalid');
 await page.locator('#job-timezone').fill('America/Chicago');
 await page.locator('#job-model').fill('custom-exact');
 await page.locator('#job-enabled').uncheck();
 await page.waitForFunction(()=>document.querySelector('#job-preview').textContent.includes('five fields'));
 await page.getByRole('button',{name:'Create job',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#jobs-error').hidden);
 check((await page.locator('#jobs-error').textContent()).includes('five fields'),'Backend rejects invalid cron');
 check(await page.locator('#job-markdown').inputValue()===markdown,'Validation preserves exact Markdown');
 await page.locator('#job-cron').fill('0 9 * * 1-5');
 await page.locator('#job-harness').selectOption('claude');
 await page.waitForFunction(()=>document.querySelector('#job-models').innerHTML.includes('claude-exact'));
 check(await page.locator('#job-model').inputValue()==='custom-exact','Harness change preserves exact custom model');
 await page.locator('#job-harness').selectOption('pi');
 await page.waitForFunction(()=>document.querySelector('#job-model-status').textContent.includes('unavailable'));
 check(await page.locator('#job-model').inputValue()==='custom-exact','Unavailable harness does not replace model');
 await page.locator('#job-harness').selectOption('codex');
 await page.getByRole('button',{name:'Create job',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-run'));
 const id=await page.evaluate(()=>new URLSearchParams(location.hash.slice(1)).get('job'));
 check(await page.locator('#job-timezone').inputValue()==='America/Chicago','Timezone round trip');
 check(await page.locator('#job-markdown').inputValue()===markdown,'Markdown byte-for-byte round trip');
 const boot=await(await page.request.get(origin+'/api/bootstrap')).json();
 const api=async operation=>{const response=await page.request.post(origin+'/api/action',{headers:paired?{}:{'X-Hey-Boss-CSRF':boot.csrf},data:{project,operation:{action:'job',operation},...(['create','edit','run_now','stop','delete','set_enabled'].includes(operation.command)?{request_id:'browser-'+Date.now()+'-'+Math.random().toString(16).slice(2)}:{})}});const value=await response.json();if(!value.ok)throw Error(JSON.stringify(value));return value;};
 const before=await api({command:'history',id,before:null,limit:20});check(before.runs.length===0,'Navigation and discovery never run a job');
 // An independent client edits the saved revision while this draft is open.
 const {job}=await api({command:'view',id});
 await api({command:'edit',id,if_revision:job.revision,definition:{...job.snapshot.definition,name:'Saved on another device'},markdown:null});
 await page.locator('#job-name').fill('My unsaved draft');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#jobs-error').textContent.includes('another device'));
 check(await page.locator('#job-name').inputValue()==='My unsaved draft','Stale edit keeps local draft');
 await page.getByRole('button',{name:'Reload saved',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-name')?.value==='Saved on another device');
 await page.locator('#job-name').fill('Weekday repository review');
 await page.getByRole('button',{name:'Save changes',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.job-panel-subtitle')?.textContent.includes('Revision 3'));
 let lost=false,requests=[];
 const loseResponse=async route=>{const body=route.request().postDataJSON();if(body.operation?.operation?.command==='run_now'){requests.push(body);if(!lost){lost=true;await route.fetch();return route.fulfill({json:{ok:false,error:{code:'offline',message:'Synthetic lost response'}}});}}return route.continue();};
 await page.route('**/api/action',loseResponse);
 await page.getByRole('button',{name:'Run now',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('#jobs-retry').hidden);
 await page.getByRole('button',{name:'Retry request',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#jobs-retry').hidden&&!document.querySelector('#job-stop').hidden);
 check(JSON.stringify(requests[0])===JSON.stringify(requests[1]),'Run now retries identical payload and request ID');
 check((await api({command:'history',id,before:null,limit:20})).runs.length===1,'Run now retry creates exactly one execution');
 await page.unroute('**/api/action',loseResponse);
 await page.getByRole('button',{name:'Resume schedule',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-enabled-toggle')?.textContent==='Pause schedule');
 await page.getByRole('button',{name:'Pause schedule',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-enabled-toggle')?.textContent==='Resume schedule');
 check((await api({command:'view',id})).job.active_run.state==='pending','Pause leaves the active execution alone');
 check(await page.locator('#job-stop').isVisible(),'Stop remains distinct while paused');
 await page.getByRole('button',{name:'Stop current run',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-stop').hidden&&document.querySelector('#job-history').textContent.includes('cancelled'));
 const stopped=await api({command:'view',id});check(!stopped.job.enabled&&!stopped.job.active_run,'Stop cancels only the execution');
 const completed=(await api({command:'history',id,before:null,limit:20})).runs[0];
 check((await page.request.post('http://127.0.0.1:52049/fixture-session',{data:{run:completed.id}})).ok(),'Seed isolated saved transcript');
 await page.getByRole('button',{name:'Refresh run history',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#job-history a[href^="/agents/session"]'));
 const sessionHref=await page.locator('#job-history a[href^="/agents/session"]').getAttribute('href');
 const task=page.locator('#job-history a').first();check((await task.getAttribute('href')).includes('issue='),'History links generated task');
 const taskHref=await task.getAttribute('href');
 for(const width of [1440,768,390])for(const theme of ['light','dark']){
  await page.setViewportSize({width,height:1000});await page.emulateMedia({colorScheme:theme});await page.waitForTimeout(220);
  await page.evaluate(()=>scrollTo(0,0));
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${width} ${theme}: no horizontal overflow`);
  await page.screenshot({path:`/tmp/hb-jobs-ui-qa/${surface}-${width}-${theme}.png`,fullPage:true});
 }
 await page.locator('#job-name').focus();await page.keyboard.press('Tab');check(await page.locator('#job-markdown').evaluate(el=>el===document.activeElement),'Keyboard reaches Markdown after name');
 await page.goto(origin+sessionHref);await page.waitForFunction(()=>document.body.textContent.includes('Synthetic saved job result.'));
 check(await page.locator('#takeover-open').isHidden(),'Job session is read-only');
 check(await page.locator('#steer-open').isHidden(),'Job session has no worker steering controls');
 await page.goto(origin+taskHref);await page.waitForFunction(()=>document.querySelector('.issue-readiness')?.textContent.includes('Scheduled job'));
 check((await page.locator('.issue-readiness').innerText()).includes('Cancelled'),'Generated task has read-only execution provenance');
 await page.goto(origin+'/jobs#'+params({project,job:id}));await page.waitForFunction(()=>document.querySelector('#job-delete'));
 await page.getByRole('button',{name:'Run now',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#job-stop').hidden);
 await page.getByRole('button',{name:'Delete job',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.job-panel-subtitle')?.textContent.includes('Deleted')&&document.querySelector('#job-history')?.textContent.includes('cancelled'));
 check((await page.locator('#job-history').textContent()).includes('cancelled'),'Deletion retains execution history');
 check(!!(await api({command:'view',id})).job.active_run,'Deletion leaves active execution alone');
 await page.getByRole('button',{name:'Stop current run',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#job-stop').hidden);
 check(!(await api({command:'view',id})).job.active_run,'Deleted schedules still allow stopping their current execution');
 await page.locator('#jobs-deleted').check();await page.waitForFunction(()=>[...document.querySelectorAll('.job-card')].some(el=>el.textContent.includes('Deleted')));
 check(!(await page.locator('#job-run').count()),'Deleted jobs have no run controls');
 check(errors.length===0,'No browser JavaScript errors');
 page.off('request',watch);return {surface,checks:checks.length,writes,job:id};
}
