import {mkdtempSync,copyFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {createServer} from 'node:net';
import {createInterface} from 'node:readline';
const root=mkdtempSync(join(tmpdir(),'hb-native-editor-web-'));
const binary=join(root,'hey-boss');copyFileSync(resolve(process.argv[2]||'target/debug/hey-boss'),binary);
const env={...process.env,HEY_BOSS_ISSUE_DB:join(root,'issues.db'),HEY_BOSS_INBOX_SOCKET:join(root,'editor.sock')};delete env.HEY_BOSS_ISSUE_HOST;
const project='named:Native editor QA';
const artifact=JSON.parse(execFileSync(binary,['artifact','--project',project,'--agent','human:boss','create','--title','Focused writing','--body','# Focus\n\nDraft safely.','--json'],{env})).artifact;
let count=0;
const bridge=createServer({allowHalfOpen:true},socket=>{let text='';socket.on('data',chunk=>text+=chunk);socket.on('end',()=>{const message=JSON.parse(text);if(message.command!=='artifact_editor')throw Error('Unexpected bridge command');const context=JSON.parse(message.question);if(context.project!==project||context.id!==artifact.id||context.body!=null)throw Error('Incorrect native context');count++;writeFileSync(join(root,'launches.json'),JSON.stringify({count,context}));socket.end(JSON.stringify({status:'ok',result:'{"ok":true}'}));});});
await new Promise(resolve=>bridge.listen(env.HEY_BOSS_INBOX_SOCKET,resolve));
const child=spawn(binary,['issue','web','--project',project,'--no-discovery','--port','0','--json'],{env,stdio:['ignore','pipe','inherit']});
const lines=createInterface({input:child.stdout});
const ready=await new Promise((resolve,reject)=>{lines.once('line',line=>resolve(JSON.parse(line)));child.once('exit',code=>reject(Error('Server exited '+code)));});
console.log(JSON.stringify({url:ready.url,project,id:artifact.id,root}));
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{child.kill('SIGTERM');bridge.close();child.once('exit',()=>{rmSync(root,{recursive:true,force:true});process.exit(0);});});
