// Isolated native web and saved Codex history; never launches real agents.
import {mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {spawn,spawnSync} from 'node:child_process';
import {createServer} from 'node:net';
import {resolve} from 'node:path';
const root=resolve('out/agents-fixture'),binary=resolve('target/debug/hey-boss');mkdirSync(root,{recursive:true});
const env={...process.env,HEY_BOSS_ISSUE_DB:root+'/issues.db',HEY_BOSS_FLEET_STATE:root,CODEX_HOME:root+'/codex'};delete env.HEY_BOSS_ISSUE_HOST;
for(const project of ['Atlas','Hey Boss','Studio']){const result=spawnSync(binary,['issue','--project',project,'create','--title','Fixture issue'],{env,encoding:'utf8'});if(result.status!==0)throw Error(result.stderr);}
const session='aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',path=root+'/codex/sessions/2026/09/19/rollout-fixture-'+session+'.jsonl';mkdirSync(resolve(path,'..'),{recursive:true});
const record=(role,text)=>JSON.stringify({type:'response_item',timestamp:'2026-09-19T12:00:00Z',payload:{type:'message',role,content:[{type:role==='user'?'input_text':'output_text',text}]}})+'\n';
writeFileSync(path,record('user','Can you make reconnecting feel effortless? Keep the conversation intact when the device briefly drops offline, and verify the changes before shipping.')+record('assistant','I’ll check how the connection recovers, then make sure your conversation stays exactly where you left it.\n\nI’m starting with the reconnect flow and the saved history.')+JSON.stringify({type:'response_item',payload:{type:'function_call',name:'exec_command',arguments:'{"cmd":"cargo test reconnect"}'}})+'\n'+JSON.stringify({type:'response_item',payload:{type:'function_call_output',output:'running 8 tests\n8 passed; 0 failed'}})+'\n'+record('assistant','The connection now recovers automatically. Your earlier messages stay in place while new activity arrives.\n\n### What I checked\n\n- Reconnecting after a short interruption\n- Reading earlier messages during live updates\n- The same flow on a narrow screen\n\n```rust\nconnection.restore(saved_cursor)?;\n```\n\nAll **8 reconnect tests passed**. I’m checking the final layout next.'));
const ids=['atlas-1','atlas-2','boss-1','studio-1','done-1'];const requests=[{sql:'DELETE FROM worker_runs',args:[]},...ids.map(id=>({sql:"INSERT INTO worker_runs(id,project_id,issue_number,job,actor_id,session_id,state,owner_pid,owner_start,machine,started_at,updated_at,finished_at,expanded_prompt) SELECT ?, 'named:Atlas',number,'{\"issue\":{\"title\":\"Fixture issue\"}}',created_by,?,'completed',1,'start','fixture',1,1,1,'Original request' FROM issues WHERE project_id='named:Atlas' LIMIT 1",args:[id,session]}))];
const database=spawnSync(binary,['fleet','database','--path',root+'/issues.db'],{input:requests.map(r=>JSON.stringify(r)+'\n').join(''),encoding:'utf8'});if(database.status!==0)throw Error(database.stderr);for(const line of database.stdout.trim().split('\n'))if(!JSON.parse(line).ok)throw Error(line);
const run=(id,project,title,state='running',finished=null)=>({id,project_id:'named:'+project,project_name:project,number:1,title,state,started_at:Date.now()-180000,finished_at:finished,last_event:'Checking the reconnect flow and preserving your conversation.'});
const snapshot=()=>({ok:true,machines:[{host:'local',hostname:'This MacBook',state:'connected',heartbeat:Date.now()/1000,workers:[{id:'local-service',pid:123,config:{enabled:true},runs:[run('atlas-1','Atlas','Make reconnecting feel effortless'),run('boss-1','Hey Boss','A calmer home for your agents'),run('done-1','Atlas','Keep every message in order','completed',Date.now()-30000)]}]},{host:'devbox',hostname:'Devbox',state:'connected',heartbeat:Date.now()/1000,workers:[{id:'remote-service',pid:124,config:{enabled:true},runs:[run('atlas-2','Atlas','Give search a little more polish')]}]},{host:'studio',hostname:'Studio Mac',state:'disconnected',heartbeat:Date.now()/1000-90,workers:[{id:'studio-service',pid:125,config:{enabled:true},runs:[run('studio-1','Studio','Finish the new listening room')]}]}],signals:[],conflicts:[]});
const socket=root+'/fleet.sock';rmSync(socket,{force:true});const sockets=new Set();
const server=createServer(client=>{sockets.add(client);client.on('close',()=>sockets.delete(client));let input='';client.on('data',chunk=>{input+=chunk;if(!input.includes('\n'))return;const request=JSON.parse(input);if(request.kind==='subscribe'){client.write('event: connected\ndata: {}\n\n');return;}client.end(JSON.stringify(request.kind==='status'?snapshot():{ok:false,error:'Read-only fixture'}));});});
server.listen(socket,()=>{const web=spawn(binary,['issue','web','--port','59641','--no-discovery','--project','Atlas','--json'],{env,stdio:['ignore','inherit','inherit']});for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>{web.kill();for(const socket of sockets)socket.destroy();server.close(()=>process.exit(0));});web.on('exit',()=>{for(const socket of sockets)socket.destroy();server.close();});});
