const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('src/issues/web/app.js', 'utf8');
const context = vm.createContext({esc:String,icon:()=>'',traceLinkForOrigin:()=>null,model:{route:{project:'example/repo'}},routeHash:route=>`#project=${route.project}&issue=${route.issue}`});
vm.runInContext(source.slice(source.indexOf('function listCommits('),source.indexOf('function renderList('))+source.slice(source.indexOf('function renderCommits('),source.indexOf('async function changeCommit(')),context);
const issue = {number:1,commits:[{sha:'abcdef1234567',url:'https://github.com/example/repo/commit/abcdef1234567'}]};
assert.equal(context.listCommits(issue,true),'','PR projects do not show commit chips');
assert.equal(context.renderCommits(issue,true),'','PR projects do not offer commit attachment');
assert.match(context.listCommits(issue,false),/abcdef1/);
assert.match(context.renderCommits(issue,false),/Attach a commit/);
assert.doesNotMatch(context.renderCommits({...issue,deleted_at:1},false),/Attach a commit/);
assert.equal(context.listCommits({number:1},false),'');
assert.equal(context.listCommits({...issue,commits:[]},false),'');
assert.doesNotMatch(context.listCommits(issue,false),/more/,'A single commit needs no overflow link');
const many = {...issue,commits:Array.from({length:6},(_,index)=>({sha:`abcdef${index}1234567`,url:`https://github.com/example/repo/commit/abcdef${index}1234567`}))};
const summary = context.listCommits(many,false);
assert.equal((summary.match(/class="issue-commit-chip"/g)||[]).length,1,'Only one commit is rendered in the list');
assert.match(summary,/abcdef5/,'Show the most recent attachment');
assert.match(summary,/>\+5 more<\/a>/,'Show the exact overflow count');
assert.match(summary,/data-issue="1"[^>]*href="#project=example\/repo&issue=1"/,'Overflow opens the issue with project context');
for(const commit of many.commits) assert.ok(context.renderCommits(many,false).includes(commit.url),'Details retain every commit');
assert.equal(context.listCommits(many,true),'','PR projects still hide all commits');
console.log('Project commit controls passed');
