const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('src/issues/web/app.js', 'utf8');
const context = vm.createContext({esc:String,icon:()=>'',traceLinkForOrigin:()=>null,model:{route:{project:'example/repo'}},routeHash:route=>`#project=${route.project}&issue=${route.issue}`});
vm.runInContext(source.slice(source.indexOf('function listCommits('),source.indexOf('function renderList('))+source.slice(source.indexOf('function renderCommits('),source.indexOf('async function changeCommit(')),context);
const issue = {number:1,commits:[{sha:'abcdef1234567',url:'https://github.com/example/repo/commit/abcdef1234567'}]};
assert.equal(context.listCommits(issue,true),'','PR projects do not show commit chips');
assert.equal(context.renderCommits(issue,true),'','PR projects do not offer commit attachment');
assert.match(context.listCommits(issue,false),/abcdef1/);
assert.match(context.renderCommits(issue,false),/Attach a commit/);
assert.doesNotMatch(context.renderCommits({...issue,deleted_at:1},false),/Attach a commit/);
assert.equal(context.listCommits({number:1},false),'');
assert.equal(context.listCommits({...issue,commits:[]},false),'');
assert.doesNotMatch(context.listCommits(issue,false),/more/,'A single commit needs no overflow link');
const many = {...issue,commits:Array.from({length:6},(_,index)=>({sha:`abcdef${index}1234567`,url:`https://github.com/example/repo/commit/abcdef${index}1234567`}))};
const summary = context.listCommits(many,false);
assert.equal((summary.match(/class="issue-commit-chip"/g)||[]).length,1,'Only one commit is rendered in the list');
assert.match(summary,/abcdef5/,'Show the most recent attachment');
assert.match(summary,/>\+5 more<\/a>/,'Show the exact overflow count');
assert.match(summary,/data-issue="1"[^>]*href="#project=example\/repo&issue=1"/,'Overflow opens the issue with project context');
for(const commit of many.commits) assert.ok(context.renderCommits(many,false).includes(commit.url),'Details retain every commit');
assert.equal(context.listCommits(many,true),'','PR projects still hide all commits');
const detail = context.renderCommits(many,false);
assert.match(detail, /^<details class="side-section commit-section">/,'Commit section starts collapsed');
assert.match(detail, /<summary[^>]*>.*Commits.*6.*<\/summary>/,'Closed summary includes the attachment count');
assert.ok(detail.indexOf('abcdef51234567') < detail.indexOf('abcdef01234567'),'Newest attachments appear first');
assert.doesNotMatch(detail, /Deduplicated commits|View agent trace|commit-trace-row/,'Rows omit repetitive helper copy and separate trace blocks');
context.traceLinkForOrigin = () => '/agents/session?session=test';
const traced = context.renderCommits(issue,false);
assert.match(traced, /class="icon-button commit-trace-link"[^>]*href="\/agents\/session\?session=test"[^>]*aria-label="Open agent trace for commit abcdef1"/,'Trace has its own accessible inline action');
assert.match(traced, /href="https:\/\/github.com\/example\/repo\/commit\/abcdef1234567" target="_blank"/,'Commit link stays separate from the trace');
console.log('Project commit controls passed');
