const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('src/issues/web/app.js', 'utf8');
const start = source.indexOf('function issueActivity(');
assert.ok(start >= 0, 'Discussion needs readable activity changes');
const context = vm.createContext({esc:s=>String(s??'').replaceAll('<','&lt;'),actorName:(id,m)=>m?`Codex ${m}`:({'human:boss':'Boss','watcher:github':'GitHub watcher'}[id]||id||'Unassigned'),icon:()=>'',date:()=>'<time>now</time>',queueActivity:()=>'',routeHash:()=>'',model:{route:{}}});
vm.runInContext(source.slice(start, source.indexOf('\nasync function ', start)), context);
const render = (action,data={}) => context.issueActivity({id:1,actor:'codex:session',created_at:1,action,data:{actor_model:'astra',...data}});
assert.match(render('assigned',{target:'github',previous_assignee:'human:boss'}),/GitHub watcher.*Boss/s);
assert.match(render('claimed',{assignee:'human:boss'}),/assigned.*Boss/s);
assert.match(render('unassigned',{previous_assignee:'human:boss'}),/unassigned.*Boss/s);
assert.match(render('assigned',{target:'machine:devbox'}),/machine:devbox/);
assert.match(render('edited',{before:{labels:['old'],title:'Old'},after:{labels:['new','<script>'],title:'New'}}),/added.*new.*&lt;script>.*removed.*old.*renamed.*Old.*New/s);
assert.match(render('edited',{before:{draft:true},after:{draft:false}}),/marked.*ready/s);
assert.match(render('triaged',{before:{assignee:'human:boss',labels:[]},after:{assignee:null,labels:['bug']}}),/unassigned.*Boss.*added.*bug/s);
assert.match(render('closed'),/Codex astra.*closed this issue/s);
assert.doesNotMatch(render('future_event'),/future_event/);
const worker = context.issueActivity({id:2,actor:'reservation:internal-id',action:'worker_selected',created_at:1,data:{worker_name:'Review worker'}});
assert.match(worker,/Review worker.*selected this issue/s);
assert.doesNotMatch(worker,/reservation:internal-id/);
console.log('Timeline presentation: 11 checks passed');
